In [22]:
import pandas as pd
import numpy as np
import rie_estimator
import csestimator
from hcaa_implementation import hcaa_alocation
import matplotlib.pyplot as plt


In [2]:
precios_americano = pd.read_csv(
    "./sp_500_original_clean.csv",
    index_col="Date",
    parse_dates=True,
)

precios_europeo = pd.read_csv(
    "./european_market_original_clean.csv",
    index_col="Date",
    parse_dates=True,
)

retornos_american = (np.log(precios_americano) - np.log(precios_americano.shift(1))).iloc[1:]
retornos_europeo = (np.log(precios_europeo) - np.log(precios_europeo.shift(1))).iloc[1:]

In [11]:
def get_optimal_k_eigen(corr_matrix, N, T):
    eigenvals = np.linalg.eigvals(corr_matrix)
    count = (eigenvals > 1 + 2 * np.sqrt(N / T) + N / T).sum()
    return count

In [ ]:
get_optimal_k_eigen()

In [ ]:
index, weights = hcaa_alocation(
            mat_X=returns,
            custom_corr=rie_estimator.get_rie,
            inverse_data=False,
            n_clusters=get_optimal_k_eigen(rie_estimator.get_rie(selected_returns), selected_returns.shape[0], selected_returns.shape[1]),
        )

In [8]:
retornos_europeo.head()

AD.AS    AGN.AS   AKZA.AS    ASM.AS   ASML.AS   BESI.AS  \
Date                                                                     
2012-01-04 -0.014088 -0.022437 -0.010624 -0.027017 -0.020262  0.002881   
2012-01-05 -0.001469 -0.019362 -0.000924  0.015559 -0.005955 -0.003073   
2012-01-06  0.002447  0.001628  0.004214  0.019167  0.009387  0.000192   
2012-01-09  0.002928 -0.008166  0.001970  0.007650  0.008991 -0.009662   
2012-01-10  0.009217  0.071199  0.023335  0.036579  0.002466  0.003876   

              DSM.AS   HEIA.AS   INGA.AS    KPN.AS  ...   NOVN.SW   PGHN.SW  \
Date                                                ...                       
2012-01-04  0.004196 -0.009320 -0.014286 -0.021930  ...  0.001837  0.000000   
2012-01-05 -0.004875 -0.000407 -0.035543 -0.021271  ... -0.001837 -0.030962   
2012-01-06 -0.005717 -0.008590 -0.008215  0.000230  ...  0.005500  0.000000   
2012-01-09 -0.008087  0.010217  0.006396 -0.001150  ... -0.011973 -0.009479   
2012-01-10  0.022051  0.001084  0.052686 -0.006349  ...  0.001867  0.003170   

              ROG.SW   SCMN.SW   SGSN.SW   SIKA.SW   SLHN.SW   SREN.SW  \
Date                                                                     
2012-01-04  0.004929 -0.003060 -0.009491 -0.007121 -0.002822  0.000407   
2012-01-05  0.000614 -0.016292 -0.005738 -0.016071 -0.031585 -0.008172   
2012-01-06  0.009172 -0.000283  0.008278 -0.003358 -0.004678 -0.014463   
2012-01-09 -0.004270 -0.004543  0.006951  0.008929 -0.026130 -0.005007   
2012-01-10 -0.002448  0.014690  0.019951  0.041888  0.009581  0.031298   

             UBSG.SW   ZURN.SW  
Date                            
2012-01-04  0.003463 -0.001854  
2012-01-05 -0.033395 -0.006982  
2012-01-06 -0.008977 -0.001870  
2012-01-09 -0.035800 -0.007044  
2012-01-10  0.034898  0.024210  

[5 rows x 270 columns]

In [14]:
def wrapper_function_cluster_2(X_matrix):
    return csestimator.get_shrinkage_est(X_matrix, alpha=0.2)

def wrapper_function_cluster_5(X_matrix):
    return csestimator.get_shrinkage_est(X_matrix, alpha=0.5)

def wrapper_function_cluster_8(X_matrix):
    return csestimator.get_shrinkage_est(X_matrix, alpha=0.8)

In [19]:
r_cuad_sample = []
r_cuad_rie = []
r_cuad_eca_2 = []
r_cuad_eca_5 = []
r_cuad_eca_8 = []

r_cuad_sample_hcaa = []
r_cuad_rie_hcaa = []
r_cuad_eca_2_hcaa = []
r_cuad_eca_5_hcaa = []
r_cuad_eca_8_hcaa = []

ipr_mark_sample = []
ipr_mark_rie = []
ipr_mark_eca_2 = []
ipr_mark_eca_5 = []
ipr_mark_eca_8 = []

ipr_mark_sample_hcaa = []
ipr_mark_rie_hcaa = []
ipr_mark_eca_2_hcaa = []
ipr_mark_eca_5_hcaa = []
ipr_mark_eca_8_hcaa = []


# 2521
for i in range(920, 930):
    # elegir los retornos de la ventana de tiempo
    selected_returns = retornos_american.iloc[i- 920 :i, :]

    # obtener los distintos estimadores
    sample_estimator = np.corrcoef(selected_returns.T)
    rie_matrix = rie_estimator.get_rie(returns = selected_returns, normalize = False, max_ones=True)
    eca_alfa_2 = csestimator.get_shrinkage_est(X_matrix = selected_returns, alpha = 0.2)
    eca_alfa_5 = csestimator.get_shrinkage_est(X_matrix = selected_returns, alpha = 0.5)
    eca_alfa_8 = csestimator.get_shrinkage_est(X_matrix = selected_returns, alpha = 0.8)
    
    # se obtienen las inversas de los estimadores
    inverse_sample = np.linalg.inv(sample_estimator)
    inverse_rie = np.linalg.inv(rie_matrix)
    inverse_eca_2 = np.linalg.inv(eca_alfa_2)
    inverse_eca_5 = np.linalg.inv(eca_alfa_5)
    inverse_eca_8 = np.linalg.inv(eca_alfa_8)

    # Se obtienen los valores óptiomos de K para el HCAA
    k_optim_sample = get_optimal_k_eigen(sample_estimator, selected_returns.shape[0], selected_returns.shape[1])
    k_optim_rie = get_optimal_k_eigen(rie_matrix, selected_returns.shape[0], selected_returns.shape[1])
    k_optim_alfa_2 = get_optimal_k_eigen(eca_alfa_2, selected_returns.shape[0], selected_returns.shape[1])
    k_optim_alfa_5 = get_optimal_k_eigen(eca_alfa_5, selected_returns.shape[0], selected_returns.shape[1])
    k_optim_alfa_8 = get_optimal_k_eigen(eca_alfa_8, selected_returns.shape[0], selected_returns.shape[1])
    
    # se obtienen pesos de markowitz
    mark_weights_sample = (inverse_sample @ np.ones(460) )/(np.ones((1,460)) @ inverse_sample @ np.ones(460) )
    mark_weigth_rie = (inverse_rie @ np.ones(460) )/(np.ones((1,460)) @ inverse_rie @ np.ones(460) )
    mark_weigth_eca_2 = (inverse_eca_2 @ np.ones(460) )/(np.ones((1,460)) @ inverse_eca_2 @ np.ones(460) )
    mark_weigth_eca_5 = (inverse_eca_5 @ np.ones(460) )/(np.ones((1,460)) @ inverse_eca_5 @ np.ones(460) )
    mark_weigth_eca_8 = (inverse_eca_8 @ np.ones(460) )/(np.ones((1,460)) @ inverse_eca_8 @ np.ones(460) )

    # se obtienen los pesos del HCAA
    index_hcaa, hcaa_weigths_sample = hcaa_alocation(mat_X = selected_returns, custom_corr = np.corrcoef, inverse_data = True, n_clusters=k_optim_sample)
    index_hcaa, hcaa_weigths_rie = hcaa_alocation(mat_X = selected_returns, custom_corr = rie_estimator.get_rie, inverse_data = False, n_clusters=k_optim_rie)
    index_hcaa, hcaa_weigths_eca_2 = hcaa_alocation(mat_X = selected_returns, custom_corr = wrapper_function_cluster_2, inverse_data = False, n_clusters=k_optim_alfa_2)
    index_hcaa, hcaa_weigths_eca_5 = hcaa_alocation(mat_X = selected_returns, custom_corr = wrapper_function_cluster_5, inverse_data = False, n_clusters=k_optim_alfa_5)
    index_hcaa, hcaa_weigths_eca_8 = hcaa_alocation(mat_X = selected_returns, custom_corr = wrapper_function_cluster_8, inverse_data = False, n_clusters=k_optim_alfa_8)
    
    # Se caclula el riesgo dentro de muestra para markowitz
    r_cuad_sample.append( 1 / (np.ones((1,460)) @ inverse_sample @ np.ones(460)))
    r_cuad_rie.append(1 / (np.ones((1,460)) @ inverse_rie @ np.ones(460)))
    r_cuad_eca_2.append( 1 / (np.ones((1,460)) @ inverse_eca_2 @ np.ones(460)))
    r_cuad_eca_5.append( 1 / (np.ones((1,460)) @ inverse_eca_5 @ np.ones(460)))
    r_cuad_eca_8.append( 1 / (np.ones((1,460)) @ inverse_eca_8 @ np.ones(460)))

    # se calcula el riesgo dentro de muestra para el HCAA
    r_cuad_sample_hcaa.append(np.array(hcaa_weigths_sample).T @ sample_estimator @ np.array(hcaa_weigths_sample))
    r_cuad_rie_hcaa.append(np.array(hcaa_weigths_rie).T @ rie_matrix @ np.array(hcaa_weigths_rie))
    r_cuad_eca_2_hcaa.append(np.array(hcaa_weigths_eca_2).T @ eca_alfa_2 @ np.array(hcaa_weigths_eca_2))
    r_cuad_eca_5_hcaa.append(np.array(hcaa_weigths_eca_5).T @ eca_alfa_5 @ np.array(hcaa_weigths_eca_5))
    r_cuad_eca_8_hcaa.append(np.array(hcaa_weigths_eca_8).T @ eca_alfa_8 @ np.array(hcaa_weigths_eca_8))

    # se calcula el IPR
    ipr_mark_sample.append((np.abs(mark_weights_sample)**4).sum())
    ipr_mark_rie.append((np.abs(mark_weigth_rie)**4).sum())
    ipr_mark_eca_2.append((np.abs(mark_weigth_eca_2)**4).sum())
    ipr_mark_eca_5.append((np.abs(mark_weigth_eca_5)**4).sum())
    ipr_mark_eca_8.append((np.abs(mark_weigth_eca_8)**4).sum())
    
    # Se calcula el IPR para el HCAA

    ipr_mark_sample_hcaa.append((np.abs(hcaa_weigths_sample)**4).sum())
    ipr_mark_rie_hcaa.append((np.abs(hcaa_weigths_rie)**4).sum())
    ipr_mark_eca_2_hcaa.append((np.abs(hcaa_weigths_eca_2)**4).sum())
    ipr_mark_eca_5_hcaa.append((np.abs(hcaa_weigths_eca_5)**4).sum())
    ipr_mark_eca_8_hcaa.append((np.abs(hcaa_weigths_eca_8)**4).sum())
 
    

In [21]:
fig, ax = plt.subplots(1,3)

[6.694757204660398e-07,
 6.214335685599362e-07,
 6.438201941640709e-07,
 6.211588549304445e-07,
 6.632248732999782e-07,
 6.632248732999782e-07,
 6.211651406366679e-07,
 6.213148519855426e-07,
 6.212402329517969e-07,
 6.384450085516657e-07]

In [5]:
ipr_mark_sample

[0.0025879749806747947,
 0.0025663985973995006,
 0.0023829352344040614,
 0.0016849250953365276,
 0.0016114165236562397,
 0.0012294753675322545,
 0.0014568565049703011,
 0.0009994786929651664,
 0.000862015237232485,
 0.0008732894051241926]

In [10]:
r_cuad_rie

[array([0.04997734]),
 array([0.05000785]),
 array([0.05029241]),
 array([0.05041346]),
 array([0.0504142]),
 array([0.05041695]),
 array([0.05054085]),
 array([0.05071052]),
 array([0.0507968]),
 array([0.05082372])]

In [6]:
r_cuad_sample

[array([0.03585049]),
 array([0.03578093]),
 array([0.03582521]),
 array([0.03581353]),
 array([0.03582637]),
 array([0.03585791]),
 array([0.03581295]),
 array([0.03600424]),
 array([0.0360504]),
 array([0.03619362])]

In [7]:
r_cuad_eca_2

[array([0.08114249]),
 array([0.07993404]),
 array([0.07985565]),
 array([0.08215633]),
 array([0.080525]),
 array([0.08095027]),
 array([0.08216482]),
 array([0.0814412]),
 array([0.08021449]),
 array([0.08031024])]

In [8]:
r_cuad_eca_5

[array([0.11359143]),
 array([0.11056825]),
 array([0.11177122]),
 array([0.11428416]),
 array([0.11357193]),
 array([0.11405534]),
 array([0.11469005]),
 array([0.11433666]),
 array([0.1118081]),
 array([0.11201145])]

In [9]:
r_cuad_eca_8

[array([0.12671828]),
 array([0.12237987]),
 array([0.12473815]),
 array([0.12737308]),
 array([0.12677546]),
 array([0.12740488]),
 array([0.1279785]),
 array([0.12797706]),
 array([0.12536748]),
 array([0.12571895])]